/* Populate tabla clientes */
INSERT INTO productos (tipo, nombre, descripcion, precio) VALUES('Componente', 'AMD Ryzen 7 3800X 3.9GHz BOX', 'Más velocidad. Más memoria. Mayor ancho de banda. Exígelos al máximo, exprime hasta la última gota de rendimiento, llévalos al límite. Los procesadores AMD Ryzen de 3 generación se diseñaron para superar todas las expectativas.', 299);
INSERT INTO productos (tipo, nombre, descripcion, precio) VALUES('Componente', 'MSI MAG Z590 TORPEDO', 'Utilizando procesadores Intel de 11.a generación, las placas base MSI Z590 cuentan con la última generación Lightning Gen 4 M.2, que es la solución de almacenamiento integrada más rápida del mercado con una velocidad de transferencia de hasta 64 Gb / s.', 189);
INSERT INTO productos (tipo, nombre, descripcion, precio) VALUES('Componente', 'MSI GeForce GTX 1660 SUPER Ventus XS OC 6GB GDDR6', 'Recién llegada, la tarjeta gráfica MSI GeForce GTX 1660 SUPER Ventus XS OC es la nueva familia de tarjetas gráficas Nvidia, una potente gráfica que viene para competir con las mejores.', 992);
INSERT INTO productos (tipo, nombre, descripcion, precio) VALUES('Componente', 'Kingston FURY Beast DDR4 3200 MHz 16GB 2x8GB CL16', 'La memoria para PC FURY Beast DDR4 de Kingston ofrece un potente aumento de rendimiento para juegos, edición de vídeo y renderización con velocidades de hasta 3733 MHz. Esta rentable actualización está disponible en velocidades de 2666 MHz a 3733 MHz.', 74);
INSERT INTO productos (tipo, nombre, descripcion, precio) VALUES('Periféricos', 'Newskill Icarus RGB IC27QRS 27" LED QuadHD 165Hz G-Sync Compatible', 'Con el nuevo monitor gamer Newskill Icarus RGB nuestra familia de monitores se expande. Esta nueva versión supone el que necesitaba para enamorar a jugadores exigentes con sus periféricos y a aquellos que solo buscan disfrutar del gaming.', 258);
INSERT INTO productos (tipo, nombre, descripcion, precio) VALUES('Periféricos', 'Newskill Serike Teclado Mecánico Gaming Full RGB Switch Blue', 'Para los amantes de los teclados mecánicos compactos, en Newskill os presentamos a Serike. Un teclado con una propuesta RGB en la que destaca un aura de retroiluminación en sus laterales y que va recorriendo todas sus teclas.', 58);


